package com.olap3.cubeexplorer.Similarity;

public enum QueryComparisonType {
    EDITDISTANCE, BY_STRUCTURE, BY_STRUCTURE_PARAMETER, BY_JACCARD_STRUCTURE, BY_JACCARD_STRUCTURE_THRESHOLD, BY_LOG, BY_INCLUSION, BY_EQUALITY, BY_ATTRIBUTE;
}
